#!/usr/bin/env python3
"""
Debug script to examine exact ANSI codes generated by StringSmith formatter.
This will help us understand what the formatter is actually outputting vs. what tests expect.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def analyze_ansi_bytes(text, label):
    """Analyze and display ANSI byte sequences in text."""
    print(f"\n{label}:")
    print(f"  Raw string: {repr(text)}")
    print(f"  Length: {len(text)}")
    print(f"  Visual: '{text}'")
    
    # Find all ANSI escape sequences
    import re
    ansi_pattern = r'\033\[[0-9;]*m'
    sequences = re.findall(ansi_pattern, text)
    if sequences:
        print(f"  ANSI sequences found: {sequences}")
        
        # Show text with ANSI codes highlighted
        highlighted = text
        for seq in set(sequences):
            highlighted = highlighted.replace(seq, f"[{seq[1:]}]")  # Remove \033, add brackets
        print(f"  With ANSI highlighted: {highlighted}")
    else:
        print(f"  No ANSI sequences found")
    
    # Show individual bytes
    byte_repr = ' '.join(f'{ord(c):02x}' if ord(c) < 128 else f'{ord(c):04x}' for c in text)
    print(f"  Hex bytes: {byte_repr}")

def test_basic_formatting():
    """Test basic color and emphasis formatting to see exact output."""
    print("=" * 60)
    print("ANSI OUTPUT DEBUG - BASIC FORMATTING")
    print("=" * 60)
    
    try:
        # Import your formatter
        from formatter import TemplateFormatter
        
        # Test 1: Simple red color
        print("\n1. SIMPLE RED COLOR TEST")
        formatter = TemplateFormatter("{{#red;message}}")
        result = formatter.format(message="test")
        analyze_ansi_bytes(result, "Your formatter output")
        
        # What tests might expect
        expected_simple = "\033[31mtest\033[0m"
        analyze_ansi_bytes(expected_simple, "Simple expected")
        
        print(f"\nMatch check: {result == expected_simple}")
        
        # Test 2: Red with prefix/suffix
        print("\n2. RED WITH PREFIX/SUFFIX")
        formatter = TemplateFormatter("{{#red;Error: ;message;}}")
        result = formatter.format(message="test")
        analyze_ansi_bytes(result, "Your formatter output")
        
        # Test 3: Bold formatting
        print("\n3. BOLD FORMATTING")
        formatter = TemplateFormatter("{{@bold;message}}")
        result = formatter.format(message="test")
        analyze_ansi_bytes(result, "Your formatter output")
        
        expected_bold = "\033[1mtest\033[0m"
        analyze_ansi_bytes(expected_bold, "Simple bold expected")
        
        # Test 4: Combined red + bold
        print("\n4. COMBINED RED + BOLD")
        formatter = TemplateFormatter("{{#red@bold;Error: ;message;}}")
        result = formatter.format(message="test")
        analyze_ansi_bytes(result, "Your formatter output")
        
        # Test 5: Multiple sections
        print("\n5. MULTIPLE SECTIONS")
        formatter = TemplateFormatter("{{#red;Error: ;msg}} {{#green;Success: ;msg2}}")
        result = formatter.format(msg="fail", msg2="pass")
        analyze_ansi_bytes(result, "Your formatter output")
        
    except ImportError as e:
        print(f"Could not import formatter: {e}")
        print("Make sure you're running this from the stringsmith directory")
    except Exception as e:
        print(f"Error during testing: {e}")
        import traceback
        traceback.print_exc()

def test_edge_cases():
    """Test edge cases that might cause ANSI issues."""
    print("\n" + "=" * 60)
    print("ANSI OUTPUT DEBUG - EDGE CASES")
    print("=" * 60)
    
    try:
        from formatter import TemplateFormatter
        
        # Test empty field
        print("\n1. EMPTY FIELD WITH FORMATTING")
        formatter = TemplateFormatter("{{#red;Error: ;message;}}")
        result = formatter.format(message="")
        analyze_ansi_bytes(result, "Empty field result")
        
        # Test missing field
        print("\n2. MISSING FIELD (SHOULD BE EMPTY)")
        result = formatter.format()
        analyze_ansi_bytes(result, "Missing field result")
        
        # Test multiple formatting on same field
        print("\n3. STACKED FORMATTING")
        formatter = TemplateFormatter("{{#red@bold@italic;message}}")
        result = formatter.format(message="test")
        analyze_ansi_bytes(result, "Stacked formatting result")
        
    except Exception as e:
        print(f"Error during edge case testing: {e}")

def compare_with_expectations():
    """Compare your output with what typical tests expect."""
    print("\n" + "=" * 60)
    print("COMPARISON WITH TEST EXPECTATIONS")
    print("=" * 60)
    
    test_cases = [
        ("{{#red;message}}", "test", "\033[31mtest\033[0m", "Simple red"),
        ("{{@bold;message}}", "test", "\033[1mtest\033[0m", "Simple bold"),
        ("{{#red@bold;message}}", "test", "\033[31m\033[1mtest\033[0m", "Red + bold"),
    ]
    
    try:
        from formatter import TemplateFormatter
        
        for template, field_value, expected, description in test_cases:
            print(f"\n{description.upper()}:")
            formatter = TemplateFormatter(template)
            actual = formatter.format(message=field_value)
            
            print(f"  Template: {template}")
            print(f"  Expected: {repr(expected)}")
            print(f"  Actual:   {repr(actual)}")
            print(f"  Match:    {actual == expected}")
            
            if actual != expected:
                print(f"  Expected contains: {[seq for seq in ['\033[31m', '\033[1m', '\033[0m'] if seq in expected]}")
                print(f"  Actual contains:   {[seq for seq in ['\033[31m', '\033[1m', '\033[0m', '\033[39m', '\033[22m'] if seq in actual]}")
    
    except Exception as e:
        print(f"Error during comparison: {e}")

if __name__ == "__main__":
    test_basic_formatting()
    test_edge_cases()
    compare_with_expectations()
    
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print("Run this script to see exactly what ANSI codes your formatter generates.")
    print("Use this information to decide how to update your test expectations.")
    print("Your defensive ANSI approach is likely better - tests should match your output.")